🧵 Lint

diff --git a/direnvrc b/direnvrc
--- a/direnvrc
+++ b/direnvrc
@@ -1,45 +1,46 @@
 layout_virtualenv() {
-  local venv_path="$1"
-  source ${venv_path}/bin/activate
+	local venv_path="$1"
+	source ${venv_path}/bin/activate
 }
 
 layout_virtualenvwrapper() {
-  local venv_path="${WORKON_HOME}/$1"
-  layout_virtualenv $venv_path
+	local venv_path="${WORKON_HOME}/$1"
+	layout_virtualenv $venv_path
 }
 
 realpath() {
-    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
+	[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
 layout_python-venv() {
-    local python=${1:-python3}
-    [[ $# -gt 0 ]] && shift
-    unset PYTHONHOME
-    if [[ -n $VIRTUAL_ENV ]]; then
-        VIRTUAL_ENV=$(realpath "${VIRTUAL_ENV}")
-    else
-        local python_version
-        python_version=$("$python" -c "import platform; print(platform.python_version())")
-        if [[ -z $python_version ]]; then
-            log_error "Could not detect Python version"
-            return 1
-        fi
-        VIRTUAL_ENV=$PWD/.direnv/python-venv-$python_version
-    fi
-    export VIRTUAL_ENV
-    if [[ ! -d $VIRTUAL_ENV ]]; then
-        log_status "no venv found; creating $VIRTUAL_ENV"
-        "$python" -m venv "$VIRTUAL_ENV"
-    fi
+	local python=${1:-python3}
+	echo "Using python interpreter: $python"
+	[[ $# -gt 0 ]] && shift
+	unset PYTHONHOME
+	if [[ -n $VIRTUAL_ENV ]]; then
+		VIRTUAL_ENV=$(realpath "${VIRTUAL_ENV}")
+	else
+		local python_version
+		python_version=$("$python" -c "import platform; print(platform.python_version())")
+		if [[ -z $python_version ]]; then
+			log_error "Could not detect Python version"
+			return 1
+		fi
+		VIRTUAL_ENV=$PWD/.direnv/python-venv-$python_version
+	fi
+	export VIRTUAL_ENV
+	if [[ ! -d $VIRTUAL_ENV ]]; then
+		log_status "no venv found; creating $VIRTUAL_ENV"
+		"$python" -m venv "$VIRTUAL_ENV"
+	fi
 
-    PATH="${VIRTUAL_ENV}/bin:${PATH}"
-    export PATH
+	PATH="${VIRTUAL_ENV}/bin:${PATH}"
+	export PATH
 }
 
 use_nvm() {
-    NODE_VERSION="$1"
+	NODE_VERSION="$1"
 
-    type nvm >/dev/null 2>&1 || . ~/.nvm/nvm.sh
-    nvm use "$NODE_VERSION"
+	type nvm >/dev/null 2>&1 || . ~/.nvm/nvm.sh
+	nvm use "$NODE_VERSION"
 }
